<?php return [
    'key' => 'sarticles.polls',
    'provider' => \Seiger\sArticles\Tables\PollsTableData::class,
    'wire_target' => 'search,perPage,applyDateRangeFilter,setSort,switchView,openCreateModal,openEditModal,saveModal,closeModal,openDeleteModal,closeDeleteModal,deleteConfirmed,addModalItem,removeModalItem,moveModalItem,goToPage,firstPage,previousPage,nextPage,goLastPage',
    'per_page' => 10,
    'per_page_options' => [10, 20, 30, 50, 100],
    'views' => ['table', 'list'],
    'default_view' => 'table',
    'default_sort' => 'updated_at',
    'default_direction' => 'desc',
    'search' => [
        'enabled' => true,
        'state' => 'search',
    ],
    'actions' => [
        [
            'key' => 'create',
            'type' => 'wire',
            'method' => 'openCreateModal',
            'icon' => 'plus',
            'label' => 'sArticles::global.add_poll',
            'tone' => 'success',
            'icon_only' => true,
        ],
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'primary',
            'icon_only' => true,
            'selection' => 'single',
        ],
        [
            'key' => 'delete',
            'type' => 'wire',
            'method' => 'openDeleteModal',
            'icon' => 'trash',
            'label' => 'global.remove',
            'tone' => 'danger',
            'icon_only' => true,
            'selection' => 'single',
        ],
    ],
    'filters' => [
        [
            'state' => 'created_at',
            'type' => 'date-range',
            'icon' => 'calendar-plus',
            'label' => 'sArticles::global.created_at',
            'default' => ['from' => '', 'to' => ''],
        ],
    ],
    'columns' => [
        [
            'key' => 'id',
            'type' => 'text',
            'label' => 'ID',
            'class' => 'evo-ui-table__number-column evo-ui-table__id-column',
            'meta_icon' => 'hash',
            'sortable' => true,
            'sort_field' => 'pollid',
            'default_direction' => 'desc',
        ],
        [
            'key' => 'question',
            'type' => 'text',
            'label' => 'sArticles::global.question',
            'class' => 'evo-ui-table__title-column',
            'meta_icon' => 'chart-bar',
            'sortable' => true,
            'sort_field' => 'question',
        ],
        [
            'key' => 'answers',
            'type' => 'chips',
            'label' => 'sArticles::global.answers',
            'meta_icon' => 'list',
            'sortable' => true,
            'sort_field' => 'answers_count',
        ],
        [
            'key' => 'answers_count',
            'type' => 'badge',
            'label' => 'sArticles::global.answers_count',
            'class' => 'evo-ui-table__number-column',
            'meta_icon' => 'list',
            'sortable' => true,
            'sort_field' => 'answers_count',
        ],
        [
            'key' => 'votes',
            'type' => 'badge',
            'label' => 'sArticles::global.votes',
            'class' => 'evo-ui-table__number-column',
            'meta_icon' => 'chart-bar',
            'sortable' => true,
            'sort_field' => 'votes',
            'default_direction' => 'desc',
        ],
        [
            'key' => 'created_at',
            'type' => 'date',
            'label' => 'sArticles::global.created_at',
            'class' => 'evo-ui-table__date-column',
            'meta_icon' => 'calendar-plus',
            'sortable' => true,
            'sort_field' => 'created_at',
            'default_direction' => 'desc',
        ],
        [
            'key' => 'updated_at',
            'type' => 'date',
            'label' => 'sArticles::global.updated_at',
            'class' => 'evo-ui-table__date-column',
            'meta_icon' => 'refresh',
            'sortable' => true,
            'sort_field' => 'updated_at',
            'default_direction' => 'desc',
        ],
    ],
    'list' => [
        'media' => false,
        'compact' => false,
        'title' => 'question',
        'subtitle' => 'answer_summary',
        'meta' => ['id', 'answers', 'answers_count', 'votes', 'created_at', 'updated_at'],
    ],
    'modal' => [
        'enabled' => true,
        'icon' => 'chart-bar',
        'size' => 'lg',
        'title_create' => 'sArticles::global.add_poll',
        'title_edit' => 'sArticles::global.edit_poll',
        'submit_label' => 'evo::global.action_save',
        'cancel_label' => 'evo::global.action_cancel',
        'fields' => [
            [
                'name' => 'question',
                'type' => 'text',
                'label' => 'sArticles::global.question',
                'rules' => ['required', 'string', 'max:255'],
                'span' => 'full',
                'live' => true,
            ],
            [
                'name' => 'answers',
                'type' => 'repeater',
                'label' => 'sArticles::global.answers',
                'hint' => 'sArticles::global.poll_answers_help',
                'add_label' => 'sArticles::global.add_answer',
                'span' => 'full',
                'layout' => 'compact',
                'rules' => ['array', 'min:1'],
                'default_item' => [
                    'answer' => '',
                    'votes' => 0,
                ],
                'fields' => [
                    [
                        'name' => 'answer',
                        'type' => 'text',
                        'label' => 'sArticles::global.answer',
                        'placeholder' => 'sArticles::global.answer',
                        'span' => 'grow',
                        'hide_label' => true,
                        'rules' => ['required', 'string', 'max:255'],
                    ],
                    [
                        'name' => 'votes',
                        'type' => 'number',
                        'label' => 'sArticles::global.votes',
                        'placeholder' => 'sArticles::global.votes',
                        'span' => 'compact',
                        'icon' => 'chart-bar',
                        'hide_label' => true,
                        'rules' => ['nullable', 'integer', 'min:0'],
                        'min' => 0,
                    ],
                ],
            ],
        ],
    ],
    'row_actions' => [
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'argument' => 'id',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'primary',
        ],
        [
            'key' => 'delete',
            'type' => 'wire',
            'method' => 'openDeleteModal',
            'argument' => 'id',
            'icon' => 'trash',
            'label' => 'global.remove',
            'tone' => 'danger',
        ],
    ],
];
