<?php return [
    'key' => 'sarticles.tags',
    'provider' => \Seiger\sArticles\Tables\TagsTableData::class,
    'wire_target' => 'search,perPage,setSort,switchView,openCreateModal,openEditModal,openActionModal,saveModal,closeModal,openDeleteModal,closeDeleteModal,deleteConfirmed,goToPage,firstPage,previousPage,nextPage,goLastPage',
    'per_page' => 10,
    'per_page_options' => [10, 20, 30, 50, 100],
    'views' => ['table', 'list'],
    'default_view' => 'table',
    'default_sort' => 'name',
    'default_direction' => 'asc',
    'search' => [
        'enabled' => true,
        'state' => 'search',
    ],
    'actions' => [
        [
            'key' => 'create',
            'type' => 'wire',
            'method' => 'openCreateModal',
            'icon' => 'plus',
            'label' => 'sArticles::global.add_tag',
            'tone' => 'success',
            'icon_only' => true,
        ],
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'primary',
            'icon_only' => true,
            'selection' => 'single',
        ],
        [
            'key' => 'delete',
            'type' => 'wire',
            'method' => 'openDeleteModal',
            'icon' => 'trash',
            'label' => 'global.remove',
            'tone' => 'danger',
            'icon_only' => true,
            'selection' => 'single',
        ],
    ],
    'modal' => [
        'enabled' => true,
        'row_dblclick' => true,
        'icon' => 'hash',
        'size' => 'sm',
        'title_create' => 'sArticles::global.add_tag',
        'title_edit' => 'sArticles::global.edit_tag',
        'submit_label' => 'evo::global.action_save',
        'cancel_label' => 'evo::global.action_cancel',
        'fields' => [
            [
                'name' => 'name',
                'type' => 'text',
                'label' => 'sArticles::global.tag_name',
                'rules' => ['required', 'string', 'max:255'],
                'span' => 'full',
            ],
        ],
    ],
    'filters' => [],
    'columns' => [
        [
            'key' => 'id',
            'type' => 'text',
            'label' => 'ID',
            'class' => 'evo-ui-table__number-column evo-ui-table__id-column',
            'meta_icon' => 'hash',
            'sortable' => true,
            'sort_field' => 'tagid',
        ],
        [
            'key' => 'name',
            'type' => 'text',
            'label' => 'sArticles::global.tag_name',
            'sortable' => true,
            'sort_field' => 'base',
        ],
        [
            'key' => 'alias',
            'type' => 'text',
            'label' => 'sArticles::global.alias',
            'sortable' => true,
            'sort_field' => 'alias',
        ],
    ],
    'list' => [
        'media' => false,
        'compact' => false,
        'labels' => true,
        'title' => 'name',
        'subtitle' => 'alias',
        'meta' => [],
    ],
    'row_actions' => [
        [
            'key' => 'texts',
            'type' => 'wire',
            'method' => 'openActionModal',
            'action_argument' => true,
            'argument' => 'id',
            'icon' => 'blockquote',
            'label' => 'sArticles::global.tag_texts',
            'tone_field' => 'has_content',
            'tone_true' => 'primary',
            'tone_false' => 'neutral',
            'modal' => [
                'enabled' => true,
                'row_dblclick' => false,
                'icon' => 'blockquote',
                'size' => 'content',
                'title' => 'sArticles::global.tag_texts',
                'submit_label' => 'evo::global.action_save',
                'data_provider' => 'tagTextModalData',
                'save_provider' => 'saveTagTextModal',
                'fields' => [
                    [
                        'name' => 'content',
                        'type' => 'editor',
                        'label' => 'sArticles::global.content',
                        'show_label' => false,
                        'rules' => ['nullable', 'string'],
                        'span' => 'full',
                        'rows' => 18,
                        'height' => '560px',
                        'editor_switcher' => false,
                        'editor_provider' => 'tagTextEditorHtml',
                    ],
                ],
            ],
        ],
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'argument' => 'id',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'primary',
        ],
        [
            'key' => 'delete',
            'type' => 'wire',
            'method' => 'openDeleteModal',
            'argument' => 'id',
            'icon' => 'trash',
            'label' => 'global.remove',
            'tone' => 'danger',
        ],
    ],
];
