<?php return [
    'key' => 'sarticles.features',
    'provider' => \Seiger\sArticles\Tables\FeaturesTableData::class,
    'wire_target' => 'search,perPage,setSort,switchView,openCreateModal,openEditModal,saveModal,closeModal,openDeleteModal,closeDeleteModal,deleteConfirmed,moveRow,reorderRow,goToPage,firstPage,previousPage,nextPage,goLastPage',
    'per_page' => 10,
    'per_page_options' => [10, 20, 30, 50, 100],
    'views' => ['table', 'list'],
    'default_view' => 'table',
    'default_sort' => 'position',
    'default_direction' => 'asc',
    'search' => [
        'enabled' => true,
        'state' => 'search',
    ],
    'reorder' => [
        'enabled' => true,
        'sort' => 'position',
        'move_provider' => 'moveRow',
        'reorder_provider' => 'reorderRow',
    ],
    'actions' => [
        [
            'key' => 'create',
            'type' => 'wire',
            'method' => 'openCreateModal',
            'icon' => 'plus',
            'label' => 'sArticles::global.add_feature',
            'tone' => 'success',
            'icon_only' => true,
        ],
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'primary',
            'icon_only' => true,
            'selection' => 'single',
        ],
        [
            'key' => 'delete',
            'type' => 'wire',
            'method' => 'openDeleteModal',
            'icon' => 'trash',
            'label' => 'global.remove',
            'tone' => 'danger',
            'icon_only' => true,
            'selection' => 'single',
        ],
    ],
    'modal' => [
        'enabled' => true,
        'row_dblclick' => true,
        'icon' => 'highlight',
        'size' => 'sm',
        'title_create' => 'sArticles::global.add_feature',
        'title_edit' => 'sArticles::global.edit_feature',
        'submit_label' => 'evo::global.action_save',
        'cancel_label' => 'evo::global.action_cancel',
        'fields' => [
            [
                'name' => 'name',
                'type' => 'text',
                'label' => 'sArticles::global.feature_name',
                'rules' => ['required', 'string', 'max:255'],
                'span' => 'full',
                'live' => true,
            ],
            [
                'name' => 'alias',
                'type' => 'alias',
                'label' => 'sArticles::global.alias',
                'source' => ['name'],
                'rules' => ['nullable', 'string', 'max:255'],
                'span' => 'full',
            ],
            [
                'name' => 'color',
                'type' => 'text',
                'label' => 'sArticles::global.color',
                'rules' => ['nullable', 'string', 'max:100'],
            ],
            [
                'name' => 'badge',
                'type' => 'text',
                'label' => 'sArticles::global.badge',
                'rules' => ['nullable', 'string', 'max:255'],
            ],
        ],
    ],
    'filters' => [],
    'columns' => [
        [
            'key' => 'id',
            'type' => 'text',
            'label' => 'ID',
            'class' => 'evo-ui-table__number-column evo-ui-table__id-column',
            'meta_icon' => 'hash',
            'sortable' => true,
            'sort_field' => 'fid',
        ],
        [
            'key' => 'name',
            'type' => 'text',
            'label' => 'sArticles::global.feature_name',
            'sortable' => true,
            'sort_field' => 'base',
        ],
        [
            'key' => 'alias',
            'type' => 'text',
            'label' => 'sArticles::global.alias',
            'sortable' => true,
            'sort_field' => 'alias',
        ],
        [
            'key' => 'color',
            'type' => 'text',
            'label' => 'sArticles::global.color',
            'sortable' => true,
            'sort_field' => 'color',
        ],
        [
            'key' => 'badge',
            'type' => 'text',
            'label' => 'sArticles::global.badge',
            'sortable' => true,
            'sort_field' => 'badge',
        ],
        [
            'key' => 'position',
            'type' => 'position',
            'label' => 'sArticles::global.position',
            'class' => 'evo-ui-table__number-column',
            'meta_icon' => 'sort-ascending',
            'sortable' => true,
            'sort_field' => 'position',
        ],
    ],
    'list' => [
        'media' => false,
        'compact' => false,
        'labels' => true,
        'title' => 'name',
        'subtitle' => 'alias',
        'meta' => ['color', 'badge', 'position'],
    ],
    'row_actions' => [
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'argument' => 'id',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'primary',
        ],
        [
            'key' => 'delete',
            'type' => 'wire',
            'method' => 'openDeleteModal',
            'argument' => 'id',
            'icon' => 'trash',
            'label' => 'global.remove',
            'tone' => 'danger',
        ],
    ],
];
