<?php

return [
    'key' => 'sarticles.tvparams',
    'provider' => \Seiger\sArticles\Tables\TvParametersTableData::class,
    'wire_target' => 'search,perPage,setSort,switchView,openCreateModal,openEditModal,saveModal,closeModal,openDeleteModal,closeDeleteModal,deleteConfirmed,moveRow,reorderRow,goToPage,firstPage,previousPage,nextPage,goLastPage',
    'per_page' => 10,
    'per_page_options' => [10, 20, 30, 50, 100],
    'views' => ['table', 'list'],
    'default_view' => 'table',
    'default_sort' => 'position',
    'default_direction' => 'asc',
    'search' => [
        'enabled' => true,
        'state' => 'search',
    ],
    'reorder' => [
        'enabled' => true,
        'sort' => 'position',
        'move_provider' => 'moveRow',
        'reorder_provider' => 'reorderRow',
    ],
    'actions' => [
        [
            'key' => 'create',
            'type' => 'wire',
            'method' => 'openCreateModal',
            'icon' => 'plus',
            'label' => 'sArticles::global.add_tv',
            'tone' => 'success',
            'icon_only' => true,
        ],
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'info',
            'icon_only' => true,
            'selection' => 'single',
        ],
        [
            'key' => 'delete',
            'type' => 'wire',
            'method' => 'openDeleteModal',
            'icon' => 'trash',
            'label' => 'global.remove',
            'tone' => 'danger',
            'icon_only' => true,
            'selection' => 'single',
        ],
    ],
    'modal' => [
        'enabled' => true,
        'row_dblclick' => true,
        'icon' => 'variable',
        'size' => 'md',
        'title_create' => 'sArticles::global.add_tv',
        'title_edit' => 'sArticles::global.edit_tv',
        'alias_provider' => 'modalAlias',
        'submit_label' => 'evo::global.action_save',
        'cancel_label' => 'evo::global.action_cancel',
        'fields' => [
            [
                'name' => 'caption',
                'type' => 'text',
                'label' => 'sArticles::global.tv_caption',
                'rules' => ['required', 'string', 'max:80'],
                'span' => 'full',
                'live' => true,
            ],
            [
                'name' => 'name',
                'type' => 'alias',
                'label' => 'sArticles::global.key',
                'rules' => ['required', 'string', 'max:50'],
                'source' => ['caption'],
            ],
            [
                'name' => 'type',
                'type' => 'select',
                'label' => 'sArticles::global.field_type',
                'rules' => ['required', 'string', 'max:50'],
                'options' => [
                    ['value' => 'text', 'label' => 'Text'],
                    ['value' => 'textarea', 'label' => 'Textarea'],
                    ['value' => 'richtext', 'label' => 'RichText'],
                    ['value' => 'image', 'label' => 'Image'],
                    ['value' => 'file', 'label' => 'File'],
                    ['value' => 'dropdown', 'label' => 'DropDown'],
                    ['value' => 'listbox', 'label' => 'Listbox'],
                    ['value' => 'listbox-multiple', 'label' => 'Listbox Multiple'],
                    ['value' => 'checkbox', 'label' => 'Checkbox'],
                ],
            ],
            [
                'name' => 'description',
                'type' => 'textarea',
                'label' => 'global.description',
                'rules' => ['nullable', 'string', 'max:255'],
                'span' => 'full',
                'rows' => 2,
            ],
            [
                'name' => 'elements',
                'type' => 'textarea',
                'label' => 'sArticles::global.tv_elements',
                'rules' => ['nullable', 'string'],
                'span' => 'full',
                'rows' => 3,
                'hint' => 'sArticles::global.tv_elements_help',
            ],
            [
                'name' => 'default_text',
                'type' => 'textarea',
                'label' => 'sArticles::global.tv_default_value',
                'rules' => ['nullable', 'string'],
                'span' => 'full',
                'rows' => 2,
            ],
            [
                'name' => 'rank',
                'type' => 'number',
                'label' => 'sArticles::global.position',
                'rules' => ['nullable', 'integer', 'min:0'],
            ],
        ],
    ],
    'filters' => [],
    'columns' => [
        [
            'key' => 'id',
            'type' => 'text',
            'label' => 'ID',
            'class' => 'evo-ui-table__number-column evo-ui-table__id-column',
            'meta_icon' => 'hash',
            'sortable' => true,
            'sort_field' => 'site_tmplvars.id',
        ],
        [
            'key' => 'caption',
            'type' => 'text',
            'label' => 'sArticles::global.tv_caption',
            'sortable' => true,
            'sort_field' => 'site_tmplvars.caption',
        ],
        [
            'key' => 'name',
            'type' => 'text',
            'label' => 'sArticles::global.key',
            'sortable' => true,
            'sort_field' => 'site_tmplvars.name',
        ],
        [
            'key' => 'type',
            'type' => 'badge',
            'label' => 'sArticles::global.field_type',
            'meta_icon' => 'variable',
            'sortable' => true,
            'sort_field' => 'site_tmplvars.type',
        ],
        [
            'key' => 'description',
            'type' => 'text',
            'label' => 'global.description',
            'sortable' => true,
            'sort_field' => 'site_tmplvars.description',
        ],
        [
            'key' => 'default_text',
            'type' => 'text',
            'label' => 'sArticles::global.tv_default_value',
        ],
        [
            'key' => 'position',
            'type' => 'position',
            'label' => 'sArticles::global.position',
            'class' => 'evo-ui-table__number-column',
            'meta_icon' => 'sort-ascending',
            'sortable' => true,
            'sort_field' => 'site_tmplvar_templates.rank',
        ],
    ],
    'list' => [
        'media' => false,
        'compact' => false,
        'title' => 'caption',
        'subtitle' => 'name',
        'meta' => ['type', 'default_text', 'position'],
    ],
    'row_actions' => [
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'argument' => 'id',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'info',
        ],
        [
            'key' => 'delete',
            'type' => 'wire',
            'method' => 'openDeleteModal',
            'argument' => 'id',
            'icon' => 'trash',
            'label' => 'global.remove',
            'tone' => 'danger',
        ],
    ],
];
