<?php return [
    'key' => 'sarticles.comments',
    'provider' => \Seiger\sArticles\Tables\CommentsTableData::class,
    'wire_target' => 'search,perPage,applyMultiFilter,applyDateRangeFilter,setFilter,setSort,switchView,togglePublished,openEditModal,saveModal,closeModal,openDeleteModal,closeDeleteModal,deleteConfirmed,goToPage,firstPage,previousPage,nextPage,goLastPage',
    'per_page' => 10,
    'per_page_options' => [10, 20, 30, 50, 100],
    'views' => ['table', 'list'],
    'default_view' => 'table',
    'default_sort' => 'created_at',
    'default_direction' => 'desc',
    'row_states' => [
        [
            'field' => 'approved',
            'value' => false,
            'class' => 'is-dimmed',
        ],
    ],
    'search' => [
        'enabled' => true,
        'state' => 'search',
    ],
    'actions' => [
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'primary',
            'icon_only' => true,
            'selection' => 'single',
        ],
        [
            'key' => 'delete',
            'type' => 'wire',
            'method' => 'openDeleteModal',
            'icon' => 'trash',
            'label' => 'global.remove',
            'tone' => 'danger',
            'icon_only' => true,
            'selection' => 'single',
        ],
    ],
    'filters' => [
        [
            'state' => 'article',
            'type' => 'multi-select',
            'icon' => 'article',
            'label' => 'sArticles::global.all_comment_articles',
            'search_label' => 'sArticles::global.filter_by_comment_article',
        ],
        [
            'state' => 'author',
            'type' => 'multi-select',
            'icon' => 'user',
            'label' => 'sArticles::global.all_comment_authors',
            'search_label' => 'sArticles::global.filter_by_comment_author',
        ],
        [
            'state' => 'created_at',
            'type' => 'date-range',
            'icon' => 'calendar-plus',
            'label' => 'sArticles::global.created_at',
            'default' => ['from' => '', 'to' => ''],
        ],
        [
            'state' => 'availability',
            'type' => 'segmented',
            'icon' => 'list',
            'label' => 'sArticles::global.comment_status_filter',
            'options' => [
                ['value' => 'all', 'icon' => 'list', 'label' => 'sArticles::global.comments_all'],
                ['value' => 'published', 'icon' => 'eye', 'label' => 'sArticles::global.comments_published'],
                ['value' => 'unpublished', 'icon' => 'eye-off', 'label' => 'sArticles::global.comments_unpublished'],
            ],
        ],
    ],
    'columns' => [
        [
            'key' => 'comment',
            'type' => 'text',
            'label' => 'sArticles::global.comment',
            'class' => 'evo-ui-table__title-column',
            'meta_icon' => 'message',
            'sortable' => true,
            'sort_field' => 's_article_comments.comment',
        ],
        [
            'key' => 'article',
            'type' => 'link',
            'label' => 'sArticles::global.article',
            'meta_icon' => 'article',
            'sortable' => true,
            'sort_field' => 'article_title',
        ],
        [
            'key' => 'author',
            'type' => 'text',
            'label' => 'sArticles::global.author',
            'meta_icon' => 'user',
            'sortable' => true,
            'sort_field' => 'author_name',
        ],
        [
            'key' => 'created_at',
            'type' => 'date',
            'label' => 'sArticles::global.created_at',
            'class' => 'evo-ui-table__date-column',
            'meta_icon' => 'calendar-plus',
            'sortable' => true,
            'sort_field' => 's_article_comments.created_at',
            'default_direction' => 'desc',
        ],
        [
            'key' => 'id',
            'type' => 'text',
            'label' => 'ID',
            'class' => 'evo-ui-table__number-column evo-ui-table__id-column',
            'meta_icon' => 'hash',
            'sortable' => true,
            'sort_field' => 's_article_comments.comid',
            'default_direction' => 'desc',
        ],
    ],
    'list' => [
        'media' => false,
        'compact' => false,
        'title' => 'comment',
        'subtitle' => false,
        'meta' => ['article', 'author', 'created_at', 'id'],
    ],
    'modal' => [
        'enabled' => true,
        'icon' => 'messages',
        'size' => 'md',
        'title_edit' => 'sArticles::global.edit_comment',
        'submit_label' => 'evo::global.action_save',
        'cancel_label' => 'evo::global.action_cancel',
        'fields' => [
            [
                'name' => 'comment',
                'type' => 'textarea',
                'label' => 'sArticles::global.comment',
                'rows' => 6,
                'span' => 'full',
                'rules' => ['required', 'string'],
            ],
            [
                'name' => 'approved',
                'type' => 'checkbox',
                'label' => 'sArticles::global.publication_status',
                'rules' => ['boolean'],
            ],
        ],
    ],
    'row_actions' => [
        [
            'key' => 'publish',
            'type' => 'wire',
            'method' => 'togglePublished',
            'argument' => 'id',
            'icon_field' => 'approved',
            'icon_true' => 'eye',
            'icon_false' => 'eye-off',
            'tone_field' => 'approved',
            'tone_true' => 'success',
            'tone_false' => 'danger',
            'label_field' => 'approved',
            'label_true' => 'sArticles::global.unpublish_comment',
            'label_false' => 'sArticles::global.publish_comment',
        ],
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'argument' => 'id',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'primary',
        ],
        [
            'key' => 'delete',
            'type' => 'wire',
            'method' => 'openDeleteModal',
            'argument' => 'id',
            'icon' => 'trash',
            'label' => 'global.remove',
            'tone' => 'danger',
        ],
    ],
];
