<?php return [
    'key' => 'sarticles.articles',
    'provider' => \Seiger\sArticles\Tables\ArticlesTableData::class,
    'wire_target' => 'search,perPage,applySelectFilter,applyMultiFilter,applyDateRangeFilter,setFilter,setSort,switchView,togglePublished,duplicateRow,duplicateSelected,openCreateModal,openEditModal,saveModal,closeModal,openDeleteModal,closeDeleteModal,deleteConfirmed,goToPage,firstPage,previousPage,nextPage,goLastPage',
    'per_page' => 10,
    'per_page_options' => [10, 20, 30, 50, 100],
    'views' => ['table', 'list'],
    'default_view' => 'table',
    'default_sort' => 'published_at',
    'default_direction' => 'desc',
    'row_states' => [
        [
            'field' => 'published',
            'value' => false,
            'class' => 'is-dimmed',
        ],
    ],
    'search' => [
        'enabled' => true,
        'state' => 'search',
    ],
    'actions' => [
        [
            'key' => 'create',
            'type' => 'wire',
            'method' => 'openCreateModal',
            'icon' => 'plus',
            'label_provider' => 'addArticleLabel',
            'tone' => 'success',
            'icon_only' => true,
        ],
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'primary',
            'icon_only' => true,
            'selection' => 'single',
        ],
        [
            'key' => 'duplicate',
            'type' => 'wire',
            'method' => 'duplicateSelected',
            'icon' => 'copy',
            'label' => 'global.duplicate',
            'tone' => 'info',
            'icon_only' => true,
            'selection' => 'single',
        ],
        [
            'key' => 'delete',
            'type' => 'wire',
            'method' => 'openDeleteModal',
            'icon' => 'trash',
            'label' => 'global.remove',
            'tone' => 'danger',
            'icon_only' => true,
            'selection' => 'single',
        ],
    ],
    'filters' => [
        [
            'state' => 'section',
            'type' => 'multi-select',
            'icon' => 'folder',
            'label' => 'sArticles::global.all_sections',
            'search_label' => 'sArticles::global.filter_by_section',
        ],
        [
            'state' => 'tag',
            'type' => 'multi-select',
            'icon' => 'hash',
            'label' => 'sArticles::global.all_tags',
            'search_label' => 'sArticles::global.filter_by_tag',
        ],
        [
            'state' => 'category',
            'type' => 'multi-select',
            'icon' => 'category',
            'label' => 'sArticles::global.all_categories',
            'search_label' => 'sArticles::global.filter_by_category',
        ],
        [
            'state' => 'feature',
            'type' => 'multi-select',
            'icon' => 'highlight',
            'label' => 'sArticles::global.all_features',
            'search_label' => 'sArticles::global.filter_by_feature',
        ],
        [
            'state' => 'published_at',
            'type' => 'date-range',
            'icon' => 'calendar',
            'label' => 'sArticles::global.published_at',
            'default' => ['from' => '', 'to' => ''],
        ],
        [
            'state' => 'availability',
            'type' => 'segmented',
            'icon' => 'list',
            'label' => 'sArticles::global.availability_filter',
            'options' => [
                ['value' => 'all', 'icon' => 'list', 'label' => 'sArticles::global.availability_all'],
                ['value' => 'published', 'icon' => 'eye', 'label' => 'sArticles::global.availability_published'],
                ['value' => 'unpublished', 'icon' => 'eye-off', 'label' => 'sArticles::global.availability_unpublished'],
            ],
        ],
    ],
    'columns' => [
        [
            'key' => 'cover',
            'type' => 'image',
            'label' => '',
            'class' => 'evo-ui-table__image-column',
        ],
        [
            'key' => 'id',
            'type' => 'text',
            'label' => 'ID',
            'class' => 'evo-ui-table__number-column evo-ui-table__id-column',
            'meta_icon' => 'hash',
            'sortable' => true,
            'sort_field' => 's_articles.id',
        ],
        [
            'key' => 'title',
            'type' => 'link',
            'label' => 'global.name',
            'class' => 'evo-ui-table__title-column',
            'sortable' => true,
            'sort_field' => 'sat.pagetitle',
        ],
        [
            'key' => 'section',
            'type' => 'link',
            'label' => 'sArticles::global.section',
            'sortable' => true,
            'sort_field' => 'section_title',
        ],
        [
            'key' => 'categories',
            'type' => 'chips',
            'label' => 'sArticles::global.categories',
        ],
        [
            'key' => 'tags',
            'type' => 'chips',
            'label' => 'sArticles::global.tags',
        ],
        [
            'key' => 'features',
            'type' => 'chips',
            'label' => 'sArticles::global.features',
        ],
        [
            'key' => 'published_at',
            'type' => 'date',
            'label' => 'sArticles::global.published_at',
            'class' => 'evo-ui-table__date-column',
            'sortable' => true,
            'sort_field' => 's_articles.published_at',
            'default_direction' => 'desc',
        ],
        [
            'key' => 'views',
            'type' => 'badge',
            'label' => 'sArticles::global.views',
            'class' => 'evo-ui-table__number-column',
            'sortable' => true,
            'sort_field' => 's_articles.views',
            'default_direction' => 'desc',
        ],
    ],
    'list' => [
        'title' => 'title',
        'subtitle' => 'section',
        'meta' => ['published_at', 'categories', 'tags', 'features', 'views'],
    ],
    'modal' => require __DIR__ . '/modal.php',
    'row_actions' => [
        [
            'key' => 'publish',
            'type' => 'wire',
            'method' => 'togglePublished',
            'argument' => 'id',
            'icon_field' => 'published',
            'icon_true' => 'eye',
            'icon_false' => 'eye-off',
            'tone_field' => 'published',
            'tone_true' => 'success',
            'tone_false' => 'danger',
            'label_field' => 'published',
            'label_true' => 'sArticles::global.unpublish_article',
            'label_false' => 'sArticles::global.publish_article',
        ],
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'argument' => 'id',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'primary',
        ],
        [
            'key' => 'duplicate',
            'type' => 'wire',
            'method' => 'duplicateRow',
            'argument' => 'id',
            'icon' => 'copy',
            'label' => 'global.duplicate',
            'tone' => 'info',
        ],
        [
            'key' => 'delete',
            'type' => 'wire',
            'method' => 'openDeleteModal',
            'argument' => 'id',
            'icon' => 'trash',
            'label' => 'global.remove',
            'tone' => 'danger',
        ],
    ],
];
