<?php return [
    "general" => [
        "authors_on" => 1,
        "categories_on" => 1,
        "comments_on" => 1,
        "features_on" => 1,
        "filter_types_on" => 1,
        "in_main_menu" => 0,
        "main_menu_order" => 11,
        "editor" => "system",
        "polls_on" => 1,
        "rating_on" => 1,
        "tag_texts_on" => 1,
        "tags_on" => 1,
        "tinymce5_theme" => "custom",
        "tvparams_on" => 1,
    ],
    "types" => [
        "article" => [
            "add_button_text" => "article",
            "cover_title_on" => 1,
            "description_on" => 1,
            "introtext_on" => 1,
            "list" => "Articles",
            "long_title_on" => 1,
            "name" => "Article",
            "publish_date_on" => 1,
            "section_template_ids" => [],
            "to_button_text" => "articles",
            "visual_editor_description" => 1,
            "visual_editor_introtext" => 1,
        ],
    ],
];
