<?php

$boolean = ['boolean'];
$text = ['nullable', 'string', 'max:255'];

return [
    'key' => 'sarticles-settings',
    'title' => 'sArticles::global.settings',
    'icon' => 'adjustments-horizontal',
    'variant' => 'config',
    'section_headers' => true,
    'source' => [
        'type' => 'config',
        'file' => 'custom/config/seiger/settings/sArticles.php',
        'root' => 'seiger.settings.sArticles',
    ],
    'actions' => [
        [
            'type' => 'save',
            'icon' => 'check',
            'label' => 'evo::global.action_save',
            'tone' => 'primary',
            'variant' => 'filled',
            'icon_only' => false,
        ],
    ],
    'tabs' => [
        ['name' => 'general', 'label' => 'sArticles::global.settings_general_tab', 'icon' => 'toggle-left'],
        ['name' => 'types', 'label' => 'sArticles::global.settings_types_tab', 'icon' => 'files'],
    ],
    'sections' => [
        [
            'key' => 'general-functionality',
            'tab' => 'general',
            'label' => 'sArticles::global.management_base_functionality',
            'icon' => 'sliders',
            'span' => 6,
            'fields' => [
                [
                    'name' => 'general.rating_on',
                    'label' => 'sArticles::global.rating',
                    'type' => 'checkbox',
                    'default' => 1,
                    'rules' => $boolean,
                    'help' => 'sArticles::global.rating_on_off_help',
                ],
                [
                    'name' => 'general.authors_on',
                    'label' => 'sArticles::global.authors',
                    'type' => 'checkbox',
                    'default' => 1,
                    'rules' => $boolean,
                    'help' => 'sArticles::global.authors_on_off_help',
                ],
                [
                    'name' => 'general.tags_on',
                    'label' => 'sArticles::global.tags',
                    'type' => 'checkbox',
                    'default' => 1,
                    'rules' => $boolean,
                    'help' => 'sArticles::global.tags_on_off_help',
                ],
                [
                    'name' => 'general.tag_texts_on',
                    'label' => 'sArticles::global.tag_texts',
                    'type' => 'checkbox',
                    'default' => 1,
                    'rules' => $boolean,
                    'help' => 'sArticles::global.tag_texts_on_off_help',
                ],
                [
                    'name' => 'general.comments_on',
                    'label' => 'sArticles::global.comments',
                    'type' => 'checkbox',
                    'default' => 1,
                    'rules' => $boolean,
                    'help' => 'sArticles::global.comments_on_off_help',
                ],
                [
                    'name' => 'general.categories_on',
                    'label' => 'sArticles::global.categories',
                    'type' => 'checkbox',
                    'default' => 1,
                    'rules' => $boolean,
                    'help' => 'sArticles::global.categories_on_off_help',
                ],
                [
                    'name' => 'general.features_on',
                    'label' => 'sArticles::global.features',
                    'type' => 'checkbox',
                    'default' => 1,
                    'rules' => $boolean,
                    'help' => 'sArticles::global.features_on_off_help',
                ],
                [
                    'name' => 'general.polls_on',
                    'label' => 'sArticles::global.polls',
                    'type' => 'checkbox',
                    'default' => 1,
                    'rules' => $boolean,
                    'help' => 'sArticles::global.polls_on_off_help',
                ],
                [
                    'name' => 'general.tvparams_on',
                    'label' => 'sArticles::global.tvs',
                    'type' => 'checkbox',
                    'default' => 1,
                    'rules' => $boolean,
                    'help' => 'sArticles::global.tvs_on_off_help',
                ],
                [
                    'name' => 'general.filter_types_on',
                    'label' => 'sArticles::global.show_filter_types',
                    'type' => 'checkbox',
                    'default' => 1,
                    'rules' => $boolean,
                ],
            ],
        ],
        [
            'key' => 'manager-behaviour',
            'tab' => 'general',
            'label' => 'sArticles::global.settings_manager_section',
            'icon' => 'layout-dashboard',
            'span' => 6,
            'fields' => [
                [
                    'name' => 'general.in_main_menu',
                    'label' => 'sArticles::global.in_main_menu',
                    'type' => 'checkbox',
                    'default' => 0,
                    'rules' => $boolean,
                    'help' => 'sArticles::global.in_main_menu_help',
                ],
                [
                    'name' => 'general.main_menu_order',
                    'label' => 'sArticles::global.main_menu_order',
                    'type' => 'number',
                    'default' => 11,
                    'min' => 0,
                    'rules' => ['integer', 'min:0'],
                    'help' => 'sArticles::global.main_menu_order_help',
                ],
                [
                    'name' => 'general.editor',
                    'label' => 'sArticles::global.settings_editor',
                    'type' => 'select',
                    'default' => 'system',
                    'rules' => ['nullable', 'string', 'max:80'],
                    'options_source' => [
                        'type' => 'rich_text_editors',
                        'include_system' => true,
                        'system_value' => 'system',
                        'system_label' => 'sArticles::global.settings_editor_system',
                    ],
                    'hint' => 'sArticles::global.settings_editor_hint',
                ],
                [
                    'name' => 'general.tinymce5_theme',
                    'label' => 'sArticles::global.settings_editor_theme',
                    'type' => 'text',
                    'default' => 'custom',
                    'rules' => ['nullable', 'string', 'max:80'],
                    'hint' => 'sArticles::global.settings_editor_theme_hint',
                ],
            ],
        ],
        [
            'key' => 'article-types',
            'tab' => 'types',
            'label' => 'sArticles::global.settings_types',
            'icon' => 'files',
            'span' => 12,
            'fields' => [
                [
                    'name' => 'types',
                    'label' => 'sArticles::global.settings_types',
                    'show_label' => false,
                    'type' => 'config-map',
                    'key_field' => '_key',
                    'key_label' => 'sArticles::global.type_key',
                    'title_field' => 'list',
                    'protect_first' => true,
                    'lock_first_key' => true,
                    'protected_keys' => ['article'],
                    'new_key' => 'type',
                    'add_label' => 'sArticles::global.add_type',
                    'delete_guard' => [
                        'table' => 's_articles',
                        'column' => 'type',
                    ],
                    'default' => [
                        'article' => [
                            'add_button_text' => 'article',
                            'cover_title_on' => 1,
                            'description_on' => 1,
                            'introtext_on' => 1,
                            'list' => 'Articles',
                            'long_title_on' => 1,
                            'name' => 'Article',
                            'publish_date_on' => 1,
                            'to_button_text' => 'articles',
                            'visual_editor_description' => 1,
                            'visual_editor_introtext' => 1,
                        ],
                    ],
                    'default_item' => [
                        '_key' => 'type',
                        'add_button_text' => 'article',
                        'cover_title_on' => 1,
                        'description_on' => 1,
                        'introtext_on' => 1,
                        'list' => 'Articles',
                        'long_title_on' => 1,
                        'name' => 'Article',
                        'publish_date_on' => 1,
                        'to_button_text' => 'articles',
                        'visual_editor_description' => 1,
                        'visual_editor_introtext' => 1,
                    ],
                    'rules' => ['array'],
                    'fields' => [
                        ['name' => 'name', 'label' => 'sArticles::global.settings_resource_name', 'type' => 'text', 'default' => 'Article', 'rules' => $text],
                        ['name' => 'list', 'label' => 'sArticles::global.list_resources', 'type' => 'text', 'default' => 'Articles', 'rules' => $text],
                        ['name' => 'add_button_text', 'label' => 'sArticles::global.add_button_text', 'type' => 'text', 'default' => 'article', 'rules' => $text],
                        ['name' => 'to_button_text', 'label' => 'sArticles::global.to_button_text', 'type' => 'text', 'default' => 'articles', 'rules' => $text],
                        ['name' => 'publish_date_on', 'label' => 'sArticles::global.published_at', 'type' => 'checkbox', 'default' => 1, 'rules' => $boolean],
                        ['name' => 'long_title_on', 'label' => 'sArticles::global.settings_long_title', 'type' => 'checkbox', 'default' => 1, 'rules' => $boolean],
                        ['name' => 'cover_title_on', 'label' => 'sArticles::global.cover_title', 'type' => 'checkbox', 'default' => 1, 'rules' => $boolean],
                        ['name' => 'introtext_on', 'label' => 'sArticles::global.settings_introtext', 'type' => 'checkbox', 'default' => 1, 'rules' => $boolean],
                        ['name' => 'visual_editor_introtext', 'label' => 'sArticles::global.settings_introtext_editor', 'type' => 'checkbox', 'default' => 1, 'rules' => $boolean],
                        ['name' => 'description_on', 'label' => 'sArticles::global.settings_description', 'type' => 'checkbox', 'default' => 1, 'rules' => $boolean],
                        ['name' => 'visual_editor_description', 'label' => 'sArticles::global.settings_description_editor', 'type' => 'checkbox', 'default' => 1, 'rules' => $boolean],
                    ],
                ],
            ],
        ],
    ],
];
