<?php

return [
    'key' => 'sarticles.authors',
    'provider' => \Seiger\sArticles\Tables\AuthorsTableData::class,
    'wire_target' => 'search,perPage,applyMultiFilter,setSort,switchView,openCreateModal,openEditModal,saveModal,closeModal,openDeleteModal,closeDeleteModal,deleteConfirmed,goToPage,firstPage,previousPage,nextPage,goLastPage',
    'per_page' => 10,
    'per_page_options' => [10, 20, 30, 50, 100],
    'views' => ['table', 'list'],
    'default_view' => 'table',
    'default_sort' => 'name',
    'default_direction' => 'asc',
    'search' => [
        'enabled' => true,
        'state' => 'search',
    ],
    'actions' => [
        [
            'key' => 'create',
            'type' => 'wire',
            'method' => 'openCreateModal',
            'icon' => 'plus',
            'label' => 'global.add',
            'tone' => 'success',
            'icon_only' => true,
        ],
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'primary',
            'icon_only' => true,
            'selection' => 'single',
        ],
        [
            'key' => 'delete',
            'type' => 'wire',
            'method' => 'openDeleteModal',
            'icon' => 'trash',
            'label' => 'global.remove',
            'tone' => 'danger',
            'icon_only' => true,
            'selection' => 'single',
        ],
    ],
    'filters' => [
        [
            'state' => 'office',
            'type' => 'multi-select',
            'icon' => 'briefcase',
            'label' => 'sArticles::global.office',
            'search_label' => 'sArticles::global.filter_by_office',
        ],
    ],
    'columns' => [
        [
            'key' => 'image',
            'type' => 'image',
            'label' => '',
            'class' => 'evo-ui-table__image-column',
        ],
        [
            'key' => 'id',
            'type' => 'text',
            'label' => 'ID',
            'class' => 'evo-ui-table__number-column evo-ui-table__id-column',
            'meta_icon' => 'hash',
            'sortable' => true,
            'sort_field' => 'autid',
        ],
        [
            'key' => 'name',
            'type' => 'text',
            'label' => 'sArticles::global.author_name',
            'sortable' => true,
            'sort_field' => 'base_name',
        ],
        [
            'key' => 'lastname',
            'type' => 'text',
            'label' => 'sArticles::global.author_lastname',
            'meta_icon' => 'user',
            'sortable' => true,
            'sort_field' => 'base_lastname',
        ],
        [
            'key' => 'alias',
            'type' => 'text',
            'label' => 'sArticles::global.alias',
            'meta_icon' => 'link',
            'sortable' => true,
            'sort_field' => 'alias',
        ],
        [
            'key' => 'gender',
            'type' => 'icon',
            'label' => 'sArticles::global.gender',
            'meta_icon' => 'gender-bigender',
            'sortable' => true,
            'sort_field' => 'gender',
        ],
        [
            'key' => 'office',
            'type' => 'text',
            'label' => 'sArticles::global.office',
            'sortable' => true,
            'sort_field' => 'base_office',
        ],
        [
            'key' => 'created_at',
            'type' => 'date',
            'label' => 'sArticles::global.created_at',
            'class' => 'evo-ui-table__date-column',
            'meta_icon' => 'calendar-plus',
            'sortable' => true,
            'sort_field' => 'created_at',
            'default_direction' => 'desc',
        ],
        [
            'key' => 'updated_at',
            'type' => 'date',
            'label' => 'sArticles::global.updated_at',
            'class' => 'evo-ui-table__date-column',
            'meta_icon' => 'refresh',
            'sortable' => true,
            'sort_field' => 'updated_at',
            'default_direction' => 'desc',
        ],
    ],
    'list' => [
        'image' => 'image',
        'title' => 'full_name',
        'subtitle' => 'office',
        'meta' => ['id', 'alias', 'gender', 'created_at', 'updated_at'],
    ],
    'modal' => [
        'enabled' => true,
        'icon' => 'user',
        'size' => 'md',
        'title_create' => 'sArticles::global.add_author',
        'title_edit' => 'sArticles::global.edit_author',
        'submit_label' => 'evo::global.action_save',
        'cancel_label' => 'evo::global.action_cancel',
        'fields' => [
            [
                'name' => 'image',
                'type' => 'image',
                'label' => 'sArticles::global.image',
                'span' => 'full',
            ],
            [
                'name' => 'name',
                'type' => 'text',
                'label' => 'sArticles::global.author_name',
                'rules' => ['required', 'string', 'max:255'],
                'live' => true,
            ],
            [
                'name' => 'lastname',
                'type' => 'text',
                'label' => 'sArticles::global.author_lastname',
                'rules' => ['nullable', 'string', 'max:255'],
                'live' => true,
            ],
            [
                'name' => 'alias',
                'type' => 'alias',
                'label' => 'sArticles::global.alias',
                'source' => ['name', 'lastname'],
                'rules' => ['nullable', 'string', 'max:255'],
            ],
            [
                'name' => 'gender',
                'type' => 'radio',
                'label' => 'sArticles::global.gender',
                'rules' => ['required', 'in:man,woman'],
                'options' => [
                    [
                        'value' => 'man',
                        'label' => 'sArticles::global.gender_man',
                        'icon' => 'gender-male',
                    ],
                    [
                        'value' => 'woman',
                        'label' => 'sArticles::global.gender_woman',
                        'icon' => 'gender-female',
                    ],
                ],
            ],
            [
                'name' => 'office',
                'type' => 'text',
                'label' => 'sArticles::global.office',
                'rules' => ['nullable', 'string', 'max:255'],
            ],
        ],
    ],
    'row_actions' => [
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'argument' => 'id',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'primary',
        ],
        [
            'key' => 'delete',
            'type' => 'wire',
            'method' => 'openDeleteModal',
            'argument' => 'id',
            'icon' => 'trash',
            'label' => 'global.remove',
            'tone' => 'danger',
        ],
    ],
];
